# Generated by Django 4.0.4 on 2022-04-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
