# Generated by Django 4.0.4 on 2022-05-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostBlock',
        ),
    ]
