# Generated by Django 4.0.4 on 2022-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AddField(
            model_name='post',
            name='cartegory',
            field=models.CharField(choices=[('Business', 'Business'), ('Real Estate', 'Realestate')], default='Real Estate', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
